import math
def calculate_complementary_error_function(x):
        return math.erfc(x)
n = 10
print("Powers of 2:", [2**x for x in range(n)])